### ISSUE TITLE
Create query for random hero

### ISSUE THREAD

**Issue by jedrzejczak** [netguru/heroes-api#33]
Assumptions:
* query should not get any parameters
* query should return Hero type

**Comment by qmixi** [comment]
Pull Request created for the `REST API` :) https://github.com/netguru/heroes-api/pull/36

**Comment by jedrzejczak** [comment]
Done
PR: #39

**Comment by qmixi** [comment]
Issue solved, since both - REST and GraphQL API are supporting `Get random hero` feature.
