### ISSUE TITLE
Status 200 when Hero is not found in DB

### ISSUE THREAD

**Issue by Arturszott** [netguru/heroes-api#40]
Hey!

Within REST part of the API it returns `null` with status 200 while expected value is 404.

https://github.com/netguru/heroes-api/blob/master/src/rest/controllers/Heroes.ts#L25

Maybe there is something in Prisma which would allow us to omit `if` statement like:

```
		if (!hero) {
			res.status(404).send('Hero not found');
		} else {
			res.send(hero);
		}
```

Let me know what you think :)

Cheers,
Artur.

**Comment by adamgajzlerowicz** [comment]
exactly my point :)

https://github.com/netguru/heroes-api/pull/42

**Comment by qmixi** [comment]
@Arturszott  @adamgajzlerowicz Solving this issue since #42 is merged. Thank you for your contribution guys! 💚 🦸‍♂️
