### ISSUE TITLE
Wrong port in console, when server is starting in graphql

### ISSUE THREAD

**Issue by flagoon** [netguru/heroes-api#54]
GIVEN: heroes-api app
WHEN: user is starting graphql server
THEN: console should show correct host and port info

Actual result: is showing port for rest api

It could be misleading, as most of queries are working fine, but some of them are not.

**Comment by serrg** [comment]
Hello, thanks for opening this issue although `PORT` variable from environment is used for REST and GraphQL server, you can not start both servers so it will be used for server you run

**Comment by flagoon** [comment]
Hey, starting both servers is not the issue. The issue is, that whatever you starting (grapthql/rest), in console, you have info that server is waiting on port 4000, but for graphql it's 4466. In docker-compose you have port configuration for this.

**Comment by serrg** [comment]
In that situation you should change `PORT` env to `4446`. `PORT` env is used for both rest and graphql servers
